version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: brainbrawler-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - brainbrawler-network

  postgres:
    image: postgres:15-alpine
    container_name: brainbrawler-db
    environment:
      POSTGRES_DB: brainbrawler
      POSTGRES_USER: brainbrawler_user
      POSTGRES_PASSWORD: brainbrawler_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - brainbrawler-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brainbrawler_user -d brainbrawler"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: brainbrawler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - brainbrawler-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainbrawler-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://brainbrawler_user:brainbrawler_password@postgres:5432/brainbrawler
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - brainbrawler-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.brainbrawler.local`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

volumes:
  postgres_data:
  redis_data:

networks:
  brainbrawler-network:
    driver: bridge 