version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: brainbrawler-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: brainbrawler
      POSTGRES_USER: brainbrawler_user
      POSTGRES_PASSWORD: brainbrawler_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - brainbrawler-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brainbrawler_user -d brainbrawler"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: brainbrawler-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - brainbrawler-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: brainbrawler-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://brainbrawler_user:brainbrawler_password@postgres:5432/brainbrawler
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-default_super_secret_key}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-default_super_refresh_secret_key}
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - brainbrawler-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brainbrawler-frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:80"  # Temporary port exposure for testing
    networks:
      - brainbrawler-net

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  brainbrawler-net:
    driver: bridge 