version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: brainbrawler-traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - brainbrawler-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.brainbrawler.com`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  postgres:
    image: postgres:15-alpine
    container_name: brainbrawler-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: brainbrawler
      POSTGRES_USER: brainbrawler_user
      POSTGRES_PASSWORD: brainbrawler_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - brainbrawler-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brainbrawler_user -d brainbrawler"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: brainbrawler-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - brainbrawler-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: brainbrawler-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://brainbrawler_user:brainbrawler_password@postgres:5432/brainbrawler
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-default_super_secret_key}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-default_super_refresh_secret_key}
      - PORT=3000
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`www.brainbrawler.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-local.rule=HostRegexp(`{host:.+}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend-local.entrypoints=web"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    networks:
      - brainbrawler-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brainbrawler-frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:80"  # Temporary port exposure for testing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`www.brainbrawler.com`)"
      - "traefik.http.routers.frontend-local.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend-local.entrypoints=web"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - brainbrawler-net

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  brainbrawler-net:
    driver: bridge 